# Generated by Django 2.1 on 2019-04-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hname_father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname_father', models.CharField(max_length=10)),
                ('fhname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booktest.Hname')),
            ],
        ),
    ]
