# Generated by Django 2.1 on 2019-04-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_hname_hname_father'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hname_father',
            old_name='hname_father',
            new_name='hname_fathers',
        ),
    ]
