# Generated by Django 2.1 on 2019-04-20 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=40)),
                ('article_time', models.DateTimeField(auto_now_add=True)),
                ('article_text', models.TextField()),
                ('article_click_volume', models.IntegerField(default=0)),
                ('article_img', models.FileField(upload_to='./static/images/')),
                ('article_category', models.CharField(max_length=100)),
                ('article_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_1.Article')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('pthone', models.CharField(max_length=30)),
                ('hobby_user', models.TextField(default='11')),
                ('speciality', models.TextField(default='sdd')),
                ('user_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
