# Generated by Django 2.1 on 2019-04-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_file',
            name='Personal_quotes',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='gender',
            field=models.CharField(default='xxx', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='hobby_user',
            field=models.TextField(default='无'),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='pthone',
            field=models.CharField(default='xxxxx', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_file',
            name='speciality',
            field=models.TextField(default='无'),
        ),
    ]
