# Generated by Django 2.1 on 2019-04-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0002_auto_20190423_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_file',
            name='user_img',
            field=models.FileField(default='user.jpg', upload_to='./static/images/users/'),
        ),
    ]
