# Generated by Django 2.1 on 2019-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0005_auto_20190424_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_num',
            field=models.IntegerField(default=0),
        ),
    ]
