# Generated by Django 2.1 on 2019-04-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_wen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=100)),
                ('choice_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wen_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='choice_wen',
            name='wen_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toupiao.Wen'),
        ),
    ]
